var carList = {
  honda: {
    City: {
      name: "City",
      model: "2024",
      seatcapacity: "6 Persons",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "20-25 Km/Liter",
      price: "4,700,000 PKR",
      color: ["white", "silver", "black",'red'],
    },
    Accord: {
      name: "Accord",
      model: "2024",
      seatcapacity: "6 Persons",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "16-20 Km/Liter",
      wheel: "24 Inch",
      price: "24,000,000 PKR",
      color: ["white", "red", "black"],
    },
    HRV: {
      name: "HRV",
      model: "2023",
      seatcapacity: "5 Persons",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "15-20 Km/Liter",
      wheel: "17 Inches",
      price: "8,890,000 PKR",
      color: ["black", "red", "white"],
    },
    BRV: {
      name: "BRV",
      model: "2024",
      seatcapacity: "6 Persons",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "18-22 Km/Liter",
      wheel: "20 Inches",
      price: "9,400,000 PKR",
      color: ["silver", "black", "white"],
    },
    Civic: {
      name: "Civic",
      model: "2023",
      seatcapacity: "4 Persons",
      fuleType: "Petrol",
      transmission: "Type/Manual",
      mileage: "15-20 Km/Liter",
      wheel: "16 Inches",
      price: "6,500,000",
      color: ["white", "silver", "black", "blue"],
    },
  },
  hyundai: {
    Santafe: {
      name: "Santafe",
      model: "2024",
      seatcapacity: "4 Persons",
      fuleType: "Petrol",
      transmission: "Type/Manual",
      mileage: "12-16 Km/Liter",
      wheel: "14 Inches",
      price: "6,500,000 PKR",
      color: ["red", "white", "black"],
    },
    Tucson: {
      name: "Tucson",
      model: "2023",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "10 to 14 KM/LITER",
      wheel: "14 Inches",
      price: "8,440,000 PKR",
      color: ["red", "white", "black"],
    },
    Venue: {
      name: "Venue",
      model: "2024",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "10 to 14 KM/LITER",
      Wheel: "17 Inches",
      price: "6,850,000 PKR",
      color: ["red", "white", "black"],
    },
    Kona: {
      name: "Kona",
      model: "2024",
      seatcapacity: "4 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "10 to 16 KM/LITER",
      Wheel: "16 Inches",
      price: "5,550,000 PKR",
      color: ["silver",'blue', "white", "black"],
    },
    Palisade: {
      name: "Palisade",
      model: "2023",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "12 to 17 KM/LITER",
      Wheel: "18 Inches",
      price: "7,850,000 PKR",
      color: ["silver", "white", "black"],
    },
  },
  toyota: {
    Yaris: {
      name: "Yaris",
      model: 2023,
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "15 to 19 Km/Liter",
      wheel: "16 Inches",
      price: "6,879,000 PKR",
      color: ["red", "white", "black"],
    },
    Corolla: {
      name: "Corolla",
      model: "2024",
      seatcapacity: "5 person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "16 to 20 Km/Liter",
      wheel: "15 Inches",
      price: "5,130,000 PKR",
      color: ["red", "white", "black"],
    },
    Premio: {
      name: "Premio",
      model: 2024,
      seatcapacity: "6 Persons",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "18-20 Km/Liter",
      wheel: "16 Inches",
      price: "5,200,000 PKR",
      color: ["red", "black", "white", "blue"],
    },
    Camry: {
      name: "Camry",
      model: "2023",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      Mileage: "14 to 18 Km/Liter",
      Wheel: "14 Inches",
      price: "23,200,000 PKR",
      color: ["red",'gray', "white", "black"],
    },
    Landcruiser: {
      name: "Landcruiser",
      model: "2023",
      seatcapacity: "8 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "10 to 12 Km/Liter",
      wheel: "20 Inches",
      price: "32,100,000 PKR",
      color: ["red", "white", "black"],
    },
    Crollacross: {
      name: "Crollacross",
      model: "2024",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      Mileage: "14 to 16 Km/Liter",
      Wheel: "16 Inches",
      price: "10,199,000 PKR",
      color: ["red", "gray","white", "black"],
    },
    Landcruiser_300: {
      name: "Landcruiser-300",
      model: "2023",
      seatcapacity: "8 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "10 to 15 Km/Liter",
      wheel: "18 Inches",
      price: "35,500,000 PKR",
      color: ["red", "white", "black"],
    },
    Fortuner: {
      name: "Fortuner",
      model: "2023",
      seatcapacity: "8 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "16 to 20 Km/Liter",
      Wheel: "18 Inches",
      price: "15,999,000 PKR",
      color: ["red", "white", "black"],
    },
    Revo: {
      name: "Revo",
      model: "2023",
      seatcapacity: "5 Person",
      extra: "Loading Area",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "10 to 15 Km/Liter",
      wheel: "18 Inches",
      price: "12,980,000 PKR",
      color: ["red", "white", "black"],
    },
    Hilux: {
      name: "Hilux",
      model: "2024",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "15 to 19 Km/Liter",
      wheel: "15 Inches",
      price: "4,500,000 PKR",
      color: ["red", "white", "black"],
    },
    Hiace: {
      name: "Hiace",
      model: "2024",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "10 to 16 Km/Liter",
      Wheel: "14 Inches",
      price: "14,570,000 PKR",
      color: ["red", "white", "black"],
    },
  },
  suzuki: {
    Swift: {
      name: "Swift",
      model: "2024",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "16 to 20 Km/Liter",
      wheel: "16 Inches",
      price: "5,500,000 PKR",
      color: ["red", "white", "black"],
    },
    Alto: {
      name: "Alto",
      model: "2023",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Manual",
      mileage: "18 to 20 Km/Liter",
      wheel: "15 Inches",
      price: "3,500,000 PKR",
      color: ["red", "white", "black"],
    },
    Cultus: {
      name: "Cultus",
      model: "2022",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "14 to 18 Km/Liter",
      wheel: "16 in",
      price: "3,000,000 PKR",
      color: ["black", "white", "gray"],
    },
    WegonR: {
      name: "Wagon R",
      model: "2024",
      seatcapacity: "5 Person",
      fuleType: "Petrol",
      transmission: "Type/Automatic",
      mileage: "16 to 20 Km/Liter",
      wheel: "15 Inches",
      price: "2,900,000 PKR",
      color: ["red","pink", "white", "black"],
    },
    Mehran: {
      name: "Mehran",
      model: "2021",
      seatcapacity: "4 Person",
      fuleType: "Petrol",
      transmission: "Type/Manual",
      mileage: "14 to 18 KM/LITER",
      wheel: "12 in",
      price: "1,500,000 PKR",
      color: ["black", "white", "silver"],
    },
  },
}
document.getElementById('main');
for(var key in carList){
    for(var key1 in carList[key]){
            var obj = carList[key][key1]
            var colorDiv = "";
            for(var i = 0; i < obj.color.length; i++){
                colorDiv += `<div class="${obj.color[i]}"></div>`
            }
            // console.log(obj)
            main.innerHTML += `
                    <div class="col-12 col-sm-12 col-md-6 col-lg-3 mb-3">
                    <div class="card" style="width: 14rem;">
                        <img src="assets/images/city1.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">${key1.toUpperCase()}  ${obj.model}</h5>
                          <p class="card-text">${obj.mileage}
                          </br>
                          ${obj.transmission}
                          </p>
                           <h6>${obj.price}</h6>
                           <div class="d-flex gap-2">
                           ${colorDiv}
                           </div>
                        </div>
                      </div>
                </div>`
        }
    }
